// import Pool from '../assets/pool.png';

// export const auctionItems = [
//   {
//     id: '1',
//     initialTime: 3600,
//     itemName: '$25k Swimming Pool',
//     image: Pool,
//     itemId: '#5829',
//     lastBid: 50,
//     bidTotal: 5050,
//     lastBidder: 'Bob',
//   },
//   {
//     id: '2',
//     initialTime: 7200,
//     itemName: 'Vintage Car',
//     image: Pool,
//     itemId: '#5678',
//     lastBid: 15000,
//     bidTotal: 50000,
//     lastBidder: 'Alice',
//   },
//   {
//     id: '3',
//     initialTime: 1800,
//     itemName: 'Rare Painting',
//     image: Pool,
//     itemId: '#9101',
//     lastBid: 2000,
//     bidTotal: 10000,
//     lastBidder: 'Charlie',
//   },
//   {
//     id: '4',
//     initialTime: 1800,
//     itemName: 'Rare Painting',
//     image: Pool,
//     itemId: '#9101',
//     lastBid: 2000,
//     bidTotal: 10000,
//     lastBidder: 'Charlie',
//   },
// ];

import Pool from '../assets/pool.png';

export const auctionItems = [
  {
    id: '1',
    initialTime: 3600,
    itemName: 'Swimming Pool',
    image: Pool,
    itemId: '#5829',
    currentBidder: 130,
    totalBidder: 250,
    lastBid: 50,
    bidTotal: 5050,
    lastBidder: 'Bob',
    bidCategory: 'pre-bid',
  },
  {
    id: '2',
    initialTime: 7200,
    itemName: 'Vintage Car',
    image: Pool,
    itemId: '#5678',
    currentBidder: 130,
    totalBidder: 250,
    lastBid: 15000,
    bidTotal: 50000,
    lastBidder: 'Alice',
    bidCategory: 'ongoing',
  },
  {
    id: '3',
    initialTime: 1800,
    itemName: 'Rare Painting',
    image: Pool,
    itemId: '#9101',
    currentBidder: 130,
    totalBidder: 250,
    lastBid: 2000,
    bidTotal: 10000,
    lastBidder: 'Charlie',
    bidCategory: 'ongoing',
  },
  {
    id: '4',
    initialTime: 1800,
    itemName: 'Rare Painting',
    image: Pool,
    itemId: '#9101',
    currentBidder: 50,
    totalBidder: 250,
    lastBid: 2000,
    bidTotal: 10000,
    lastBidder: 'Charlie',
    bidCategory: 'pre-bid',
  },
];
